name: Calcul isochrones Géoplateforme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  calcul-isochrones:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer dépendances
        run: |
          pip install -r backend/requirements.txt

      - name: Calculer les isochrones
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python isochrones.py
